name: Deploy App and Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Clona o repositório
        uses: actions/checkout@v4

      - name: Configura o interpretador Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instala bibliotecas Python
        run: |
          python -m pip install --upgrade pip
          pip install --requirement requirements.txt

      - name: Constrói páginas HTML com MKDocs
        run: mkdocs build 

      - name: Move a documentação para a pasta /docs
        run: |
          rm -rf docs  # Apaga a pasta 'docs' original (que continha só o index.md)
          mv site docs # Renomeia a pasta 'site' (com o resultado do build) para 'docs'

      - name: Configura o GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload do artefato para o GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Publica no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clona o repositório
        uses: actions/checkout@v4

      - name: Instala Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Instala dependências
        run: npm install

      - name: Executa testes automatizados (QUnit)
        run: npm test
